"""Add address field to LocationAuthority

Revision ID: 974093df1562
Revises: 
Create Date: 2025-08-07 19:39:41.207409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974093df1562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_authority', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.drop_column('type')

    with op.batch_alter_table('lorry_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_wheels', sa.Integer(), nullable=True))

    with op.batch_alter_table('route_stop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority_id', sa.Integer(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('from', 'intermediate', 'to', name='stop_type'),
               nullable=False)
        batch_op.create_foreign_key(None, 'location_authority', ['authority_id'], ['id'])
        batch_op.drop_column('authority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_stop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('type',
               existing_type=sa.Enum('from', 'intermediate', 'to', name='stop_type'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('authority_id')

    with op.batch_alter_table('lorry_details', schema=None) as batch_op:
        batch_op.drop_column('no_of_wheels')

    with op.batch_alter_table('location_authority', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
