"""Add state field to LetterRecord

Revision ID: f639435e911a
Revises: 
Create Date: 2025-08-11 18:58:17.131885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f639435e911a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Enum('DRAFT', 'PROPOSAL', 'APPROVED', 'CANCELLED', name='letter_state'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_record', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
